### ISSUE TITLE
命令行直接输入ilus会报错：AttributeError: 'Namespace' object has no attribute 'sysconf'

### ISSUE THREAD

**Issue by Sagityq** [ShujiaHuang/ilus#1]
如题：
pip安装完ilus后，命令行直接输入ilus会报错：
```shell
Traceback (most recent call last):
  File "/home/zhiyq/.conda/envs/ilus/bin/ilus", line 8, in <module>
    sys.exit(main())
  File "/home/zhiyq/.conda/envs/ilus/lib/python3.7/site-packages/ilus/main.py", line 100, in main
    with open(kwargs.sysconf) as C:
AttributeError: 'Namespace' object has no attribute 'sysconf'
```
我在windows下和Linux下都试过，会报同样的错。
Linux下Python 3.7.10；
windows下Python 3.8.8。

二者都使用的是conda环境中的python。

请问是什么原因？

**Comment by ShujiaHuang** [comment]
感谢你的反馈，是一个bug，当你仅仅只是输入 ilus 的时候就会有这个问题，而如果直接附带了 命令参数就不会有这个问题了，比如： `ilus --help` 或者 `ilus WGS` 的时候都可以正常使用。我稍后会修复这个bug

**Comment by ShujiaHuang** [comment]
> 如题：
> pip安装完ilus后，命令行直接输入ilus会报错：
> 
> ```shell
> Traceback (most recent call last):
>   File "/home/zhiyq/.conda/envs/ilus/bin/ilus", line 8, in <module>
>     sys.exit(main())
>   File "/home/zhiyq/.conda/envs/ilus/lib/python3.7/site-packages/ilus/main.py", line 100, in main
>     with open(kwargs.sysconf) as C:
> AttributeError: 'Namespace' object has no attribute 'sysconf'
> ```
> 
> 我在windows下和Linux下都试过，会报同样的错。
> Linux下Python 3.7.10；
> windows下Python 3.8.8。
> 
> 二者都使用的是conda环境中的python。
> 
> 请问是什么原因？


这个问题已经修复，你重新用 `pip install ilus --upgrade` 更新一下即可正常使用了。

**Comment by Sagityq** [comment]
好的谢谢！
